apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: sample-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sample-flask-service
    spec:
      containers:
      - name: sample-flask-service
        image: jikuma/simple-service:4
        env:
        - name: SERVICE_REVISION
          value: "4"
        ports:
        - containerPort: 5000